# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cijoe_passenger}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Marney", "Tony Pitale"]
  s.date = %q{2010-08-03}
  s.default_executable = %q{cijoep}
  s.description = %q{Generates a CIJoe passenger instance with projects that automatically build.}
  s.email = %q{gotascii@gmail.com}
  s.executables = ["cijoep"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".bundle/config",
     ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/cijoep",
     "cijoe_passenger.gemspec",
     "lib/cijoe_passenger.rb",
     "lib/cijoe_passenger/add.rb",
     "lib/cijoe_passenger/git.rb",
     "lib/cijoe_passenger/install.rb",
     "lib/cijoe_passenger/project.rb",
     "lib/cijoe_passenger/scan.rb",
     "spec/cijoe_passenger/add_spec.rb",
     "spec/cijoe_passenger/git_spec.rb",
     "spec/cijoe_passenger/install_spec.rb",
     "spec/cijoe_passenger/project_spec.rb",
     "spec/cijoe_passenger/scan_spec.rb",
     "spec/spec_helper.rb",
     "templates/config.ru",
     "templates/config/cijoe_passenger.conf.tt",
     "templates/config/config.yml.tt",
     "templates/log/access_log",
     "templates/log/error_log",
     "templates/public/index.html"
  ]
  s.homepage = %q{http://github.com/vigetlabs/cijoe_passenger}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Makes CIJoe awesomer.}
  s.test_files = [
    "spec/cijoe_passenger/add_spec.rb",
     "spec/cijoe_passenger/git_spec.rb",
     "spec/cijoe_passenger/install_spec.rb",
     "spec/cijoe_passenger/project_spec.rb",
     "spec/cijoe_passenger/scan_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

